### ISSUE TITLE
Error account have sr25519 key, it must have ed25519 key

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/terraform-provider-grid#109]
When deploying caprover through terraform, I get the error 

mycaprover$ terraform apply -parallelism=1
╷
│ Error: the account associated with the given mnemonics have sr25519 key, it must have ed25519 key
│ 
│   with provider["registry.terraform.io/threefoldtech/grid"],
│   on caprover.tf line 9, in provider "grid":
│    9: provider "grid" {
│ 
╵

**Comment by gmachtel** [comment]
I know conversion was ongoing to sr keys, issue to be kept informed about when correction is available

**Comment by OmarElawady** [comment]
Judging from the error message, you are using 0.1.13 or an older version. In 0.1.14, you can specify key_type to be ed25519 or sr25519. The sr25519 as of now won't work on testnet as it's not yet updated with this zos update.
