### ISSUE TITLE
Docs needs more info

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#116]
1. the docs in home page doesn't contains any description 
2. should contains links to resources docs in docs directory
3. resource docs all have the same description template `Sample resource in the Terraform provider scaffolding.` this should be changed/adapted to each resource for example check `terraform-provider-grid/docs/resources/kubernetes.md`

**Comment by OmarElawady** [comment]
Updated in https://github.com/threefoldtech/terraform-provider-grid/pull/117
