### ISSUE TITLE
Parallelism is limited to 1

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/terraform-provider-grid#12]
## Description

Terraform by default uses parallelism equal to 10 which means multiple deployments can be created in parallel. This is not possible in the 0-OS grid v3. Not very clear about technical details but it includes creating multiple blocks with some sequence number which must be incremented after each block. When both are deployed in parallel they send the same sequence number which causes one of them to fail.

## Reporting by the plugin

You'd get an error in the deployment that failed

### Before deploying

append --parallelism=1 to every command (apply, destroy)

### After failed deployment

execute `terraform apply --parallelism=1` again, it should deploy the failed ones

## Fixes

Not possible from terraform side.

**Comment by MarioBassem** [comment]
maybe we should investigate having a substrate connection manager that handles requests sequentially, and let the terrafform provider run in parallel.
