### ISSUE TITLE
terraform  deployment responds with "account not found"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/terraform-provider-grid#120]
- terraform version:
```
/opt/mytrunk/terraform/single_node$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of threefoldtech/grid...
- Installing threefoldtech/grid v0.1.15...
- Installed threefoldtech/grid v0.1.15 (self-signed, key ID 77AB02E5CA9698A3)
```
- Created a "new" account in the polkadot interface in the browser
![image](https://user-images.githubusercontent.com/13766992/142822005-3c3d00f6-47cd-4439-801b-cf6333911944.png)

- portal.test.grid.tf recognizes the account
![image](https://user-images.githubusercontent.com/13766992/142822413-7910cbdc-09d0-41f3-82b9-0dfd3076516b.png)

- when trying to deploy the [single VM](https://github.com/threefoldtech/terraform-provider-grid/tree/development/examples/resources/singlenode) I input the mnemonic belonging to the account and I get this error message
```
~/opt/mytrunk/terraform/single_node$ terraform apply
provider.grid.mnemonics
  Enter a value: always borrow twenty negative call hundred ceiling leisure sunset enact feel frown

╷
│ Error: account not found
│ 
│   with provider["registry.terraform.io/threefoldtech/grid"],
│   on <input-prompt> line 1:
│   (source code not available)
```

There is not mention anymore in the example to connect to testnet - do I need to add a line specifying to deploy on testnet.
```
terraform {
  required_providers {
    grid = {
      source = "threefoldtech/grid"
    }
  }
}

provider "grid" {
}
```

**Comment by weynandkuijpers** [comment]
Needed to create a new account by using the portal.  I figured out that we now use a new key pair type and that the "old" account is no longer valid

**Comment by danielcwg** [comment]
@weynandkuijpers I'm getting the same error: "account not found".  What do you mean by "create a new account using the portal"?   I have a new account created and funded on main net. I was able to deploy with it a full vm using the play.grid.tf. 
I'm using "threefoldtech/grid v1.5.9"

**Comment by danielcwg** [comment]
Found the issue..  Terraform provider is using the wrong network (dev instead of main) and this gives the "account not found" error. See #364
