### ISSUE TITLE
Add planetary option for kubernetes masters and workers

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/terraform-provider-grid#125]
https://registry.terraform.io/providers/threefoldtech/grid/latest/docs/resources/kubernetes#nested-schema-for-master
https://registry.terraform.io/providers/threefoldtech/grid/latest/docs/resources/kubernetes#nested-schema-for-workers

**Comment by OmarElawady** [comment]
implemented in https://github.com/threefoldtech/terraform-provider-grid/pull/134
