### ISSUE TITLE
can't access metrics after deploy QSFS

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/terraform-provider-grid#141]
with devnet and this [main.tf](https://gist.github.com/mhost39/924c780dc50afb85f611155c1dc96263)
steps:
after deploy successful 
i can ssh onto VM by ygg ip
but when i try to access metrics ip i got 
```
ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: http://[303:60c2:bb79:5147:a42e:6450:44fb:b730]:9100/metrics

Connection to 303:60c2:bb79:5147:a42e:6450:44fb:b730 failed.

The system returned: (101) Network is unreachable

The remote host or network may be down. Please try the request again.

Your cache administrator is webmaster.
```

**Comment by OmarElawady** [comment]
What is the contract id and is the deployment still active?

**Comment by OmarElawady** [comment]
Network is unreachable seems to be a local firewall or network problem, and the response seems to be not from the grid based on (webmaster cache, ...).
