### ISSUE TITLE
sync terraform state to TFChain

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/terraform-provider-grid#146]
should use the same format as the typescript client.

this is to be able to list and manage deployments and contracts through the client/weblets

**Comment by mohamedamer453** [comment]
Verified on devnet.

Terrafrom state is now synced with tfchain an the user is now able to check the details of any contract deployed from terraform through the Contracts tab in the grid weblets.

[TF Playground (6).webm](https://user-images.githubusercontent.com/101194226/202893192-ee8c1261-7355-4e1c-b7ce-01a91f4bb08f.webm)
