### ISSUE TITLE
validate flists used

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/terraform-provider-grid#163]
get request on the flist url + `.md5` suffix as used in zos https://github.com/threefoldtech/zos/blob/2f1ee150a8026204833ff4ddca1ec093106fb0a1/pkg/flist/flist.go#L553

**Comment by OmarElawady** [comment]
the flists is validated with the inputted `flist_checksum` if present (to avoid breaking examples, and it arguably makes sense this way anyway).
https://github.com/threefoldtech/terraform-provider-grid/pull/166
