### ISSUE TITLE
Improve error when Yggdrasil isn't working

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/terraform-provider-grid#17]
Currently, a user who hasn't added peers to their Yggdrasil config won't get any hint that this is the issue, either from Yggdrasil (out of our scope) or from Terraform (we can improve). This is the current error from our plugin:

```
grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
grid_network.net1: Still creating... [20s elapsed]
grid_network.net1: Still creating... [30s elapsed]
╷
│ Error: failed to get node free wg port: failed to list wg ports: could not send request and all retries done
```

Suggest: add some reference to Yggdrasil, or even suggest to the user to check that it's running and properly configured with peers.

**Comment by OmarElawady** [comment]
An initial check was added with a link to the troubleshooting [page](https://github.com/threefoldtech/terraform-provider-grid/blob/development/TROUBLESHOOTING.md) with yggdrasil and other issues that faced new users.
