### ISSUE TITLE
err: invalid character 'l' looking for beginning of value

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/terraform-provider-grid#180]
getting this error a lot when using grid_scheduler.sched

"couldn't fetch node {n}: invalid character 'l' looking for beginning of value"

I need to keep retrying `terraform apply` till it eventually succeeds.

maybe we could enhance the logic to skip the `likely down` nodes when checking the nodes' capacity instead of exiting with an error.

**Comment by OmarElawady** [comment]
Retrying is done in terraform, and grid proxy on devnet is updated with timeout increase.

Specifically for this issue, filtering nodes are done without contacting the node which should prevent this error from appearing (at least on this stage).
