### ISSUE TITLE
prequest steps for use terraform provider 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/terraform-provider-grid#19]
- install yggdrasil and create twin from https://github.com/threefoldtech/TFGRID/blob/development/wiki/tfgrid_substrate/substrate/grid_substrate_getting_started.md

- download msgbusd and ```chmod +x msgbusd``` then run ```./msgbusd --twin your_twin_id --debug all```
- then follow the [README.md](https://github.com/threefoldtech/terraform-provider-grid/blob/development/README.md) for start with terraform

**Comment by OmarElawady** [comment]
msgbus is no longer required. It's embedded in the plugin.

**Comment by mhost39** [comment]
this link need to be in docs as refrence for new users  https://github.com/threefoldtech/TFGRID/blob/development/wiki/tfgrid_substrate/substrate/grid_substrate_getting_started.md
