### ISSUE TITLE
Terratest Environment Variables

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#213]
All the test cases made with terratest that use the following command to check for environment variables 
```
res, _ := tests.RemoteRun("root", pIP, "printenv")
```
needs to be changed to 
```
res, _ := tests.RemoteRun("root", pIP, "cat /proc/1/environ")
```
because using the `printenv` command doesn't print the environment variables and they can only be available through process id 1 according to this [issue](https://github.com/threefoldtech/test_feedback/issues/47)

**Comment by MarioBassem** [comment]
fixed here: https://github.com/threefoldtech/terraform-provider-grid/commit/482772817f879d551f736eba75e8ddd1ab89ebe9
