### ISSUE TITLE
TC175:  Deploy k8s with non exist network

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/terraform-provider-grid#214]
Got unexpected error:

```bash
Error: couldn't load deployer data: couldn't parse node id: strconv.ParseUint: parsing "x": invalid syntax

...

Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1;
Error: couldn't load deployer data: couldn't parse node id: strconv.ParseUint: parsing "x": invalid syntax

on main.tf line 20, in resource "grid_kubernetes" "k8s1":
20: resource "grid_kubernetes" "k8s1" {
}
```

[main.zip](https://github.com/threefoldtech/test_feedback/files/8462727/main.zip)

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/174

**Comment by OmarElawady** [comment]
As indicated [here](https://github.com/threefoldtech/terraform-provider-grid/blob/development/docs/resources/kubernetes.md#required), the `nodes_ip_range` should be assigned from the network object as in the example [here](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/k8s/main.tf#L22)
