### ISSUE TITLE
add  Namespace and IPs in terraform state

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/terraform-provider-grid#22]
when deploy zdbs can't got the Namespace and IPs in outputs
![screeeeeeen](https://user-images.githubusercontent.com/31102305/132127530-3670467c-5b4a-48d8-a9e2-211c7d11c47e.png)

**Comment by xmonader** [comment]
Why don't you edit the example for ZDBs in a PR?

**Comment by OmarElawady** [comment]
It's not yet exposed in the terraform state

**Comment by OmarElawady** [comment]
It's now done in `0.1.1`. [example](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/disks/main.tf)
