### ISSUE TITLE
Terraform vCPU upgrade problem

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/terraform-provider-grid#220]
Same deployment as previous issue (1 vCPU 2 GB RAM)

### Steps to Reproduce

1. `terraform apply --parallelism=1`
2. Modify VM from 1 to 2 vCPU
3. `terraform apply --parallelism=1` --> error : error sending deployment to the node: workload 'zmachine' does not support upgrade: upgrade validation error
4. New try : `terraform apply --parallelism=1` 

```
grid_network.netk8s1: Refreshing state... [id=24fd1c0e-2ce7-4adb-a2e7-375e4c1b3e35]
grid_deployment.t3k8s: Refreshing state... [id=4342]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

No more error messages....

**Comment by OmarElawady** [comment]
Upgrade support isn't supported for VMs on zos side, so 1-3 is expected. Step 4 is a bug in terraform in that the state is updated (from 1 vcpu to 2) even after the upgrade failure. And the plugin doesn't update this part of the deployment from the node. It should (in the read phase), fetch all information (now it fetches only a part of it).

**Comment by OmarElawady** [comment]
Fixed in https://github.com/threefoldtech/terraform-provider-grid/pull/244
