### ISSUE TITLE
Yggdrasil instability blocks deployments

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/terraform-provider-grid#23]
Original issue logged below was resolved by restarting Yggdrasil, even though logs from Yggdrasil don't make is obvious that there was any issue.

Need to understand how to check if Yggdrasil is functioning properly as needed to make deployments work. When it's not, need to understand if issue can be resolved by changes to peer list. If that's the case, providing a known working peer configuration may help.

With clarity on what's happening within Yggdrasil to cause this, we can at least open an issue on their end to see if they can implement a solution. In the meantime, perhaps we can at least include a clear error message instructing the user to try restarting the service.

----------------

Running Terraform apply on a simple VM deployment fails with RMB communication errors. Tried deployment on several nodes with same result.

Two debug logs from Terraform, one from me and one from Weynand:

https://gist.github.com/scottyeager/67ced8973ace7cc385aa351f89cc4102
https://gist.github.com/weynandkuijpers/ddfea54b0344056d7db1440a96e7855a

Running RMB separately for me shows:

```
[+] reply from external agent
{"ver":1,"uid":"5.4","cmd":"zos.network.list_wg_ports","exp":3600,"try":0,"dat":"Wzc1MjgsNjQ1Niw5OTQzLDk5NDQsOTk0NSw2ODM1LDY2OTQsMjE2Ml0=","src":5,"dst":[53],"ret":"msgbus.system.reply","shm":"","now":1631002303,"err":""}
threefoldtech.rmb.server.Message{
    version: 1
    id: '5.4'
    command: 'zos.network.list_wg_ports'
    expiration: 3600
    retry: 0
    data: 'Wzc1MjgsNjQ1Niw5OTQzLDk5NDQsOTk0NSw2ODM1LDY2OTQsMjE2Ml0='
    twin_src: 5
    twin_dst: [53]
    retqueue: 'msgbus.system.reply'
    schema: ''
    epoch: 1631002303
    err: ''
}
[+] message reply for me, fetching backlog
[+] cycle waiting
[+] scrubbing
[+] checking retries
threefoldtech.rmb.server.Message{
    version: 1
    id: ''
    command: 'zos.network.list_wg_ports'
    expiration: 3600
    retry: 0
    data: 'bnVsbA=='
    twin_src: 0
    twin_dst: [55]
    retqueue: 'd8a1917e-ebc6-4190-a157-5d23060ff5dd'
    schema: ''
    epoch: 0
    err: ''
}
original return queue: d8a1917e-ebc6-4190-a157-5d23060ff5dd
[+] resolving twin: 55
fish: Job 1, './msgbusd --twin 53 --debug all' terminated by signal SIGSEGV (Address boundary error)
```

Whereas Weynand sees:
```
http://306:50f:b86a:e850:21bc:ce3d:7927:1ebc:8051/zbus-remote
dial_tcp failed
[-] could not send message to remote msgbus
[-] no more retry, replying with error
[+] cycle waiting
```

**Comment by scottyeager** [comment]
I also see errors in Yggdrasil's output, which appear to resolve:

```
2021/09/07 04:04:37 Disconnected TLS: 202:6aca:f292:8ddc:1e2f:1a2d:a645:bffb@fe80::443:baf3:1527:d52e%wlp3s0, source fe80::4e34:88ff:fea0:3b2e%wlp3s0; error: read tcp [fe80::4e34:88ff:fea0:3b2e%wlp3s0]:38103->[fe80::443:baf3:1527:d52e%wlp3s0]:63964: i/o timeout
2021/09/07 04:04:38 Disconnected TLS: 202:9f:d453:a6ad:a6bf:6295:15d9:302e@45.147.198.155, source 192.168.1.5; error: read tcp 192.168.1.5:50412->45.147.198.155:6010: i/o timeout
2021/09/07 04:04:39 Disconnected TCP: 200:ad1e:2e16:553f:62bf:7447:2807:446@185.165.169.234, source 192.168.1.5; error: read tcp 192.168.1.5:33344->185.165.169.234:8880: i/o timeout
2021/09/07 04:05:22 Connected TCP: 200:ad1e:2e16:553f:62bf:7447:2807:446@185.165.169.234, source 192.168.1.5
2021/09/07 04:05:22 Connected TLS: 202:9f:d453:a6ad:a6bf:6295:15d9:302e@45.147.198.155, source 192.168.1.5
```

**Comment by OmarElawady** [comment]
I had the same error message, and the node's yggdrasil ip wasn't accessible with me or @AhmedHanafy725 . But we could ping other yggdrasil ips. So it may be an issue with the nodes' connection stability and not necessarily the client's.

**Comment by xmonader** [comment]
@scottyeager I understand, we are working atm on a proxy that will be reachable over http(s) and remvoe the requirement of redis, yggdrasil on the host.

**Comment by xmonader** [comment]
Not needed anymore after the integration with the gridproxy be default
