### ISSUE TITLE
Failing mainnet deploy: failed to submit extrinsic: Priority is too low

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/terraform-provider-grid#235]
### Terraform Version
```
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/threefoldtech/grid v0.1.31
```

### Terraform Configuration Files
```hcl
resource "grid_network" "net1" {
    nodes = [293]
    ip_range = "10.139.0.0/16"
    name = "bscnodenetw2"
    description = "BSC full node network2"
    add_wg_access = true
}
resource "grid_deployment" "d1" {
  node = 293
  network_name = grid_network.net1.name
  ip_range = lookup(grid_network.net1.nodes_ip_range, 293, "")
  disks {
    name = "root"
    size = 1750
  }
    vms {
    name = "bscfullnode"
    description ="Binance Smart Chain full node"
    flist = "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist"
    cpu = 32
    publicip = true
    publicip6 = false
    memory = 65536
#    rootfs_size = 25000
    mounts {
        disk_name = "root"
        mount_point = "/data"
    }
    planetary = true
    env_vars = {
      SSH_KEY ="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x"
    }
  }
}
```

### Expected Behavior
Just deploy the vm. I'm having this behavior not only with this ZOS node 293, but happens regularly.

### Actual Behavior
Errors below

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Different errors
First error was after the initial deploy: terraform apply -parallelism=1 -auto-approve

```
grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
grid_network.net1: Still creating... [20s elapsed]
grid_network.net1: Creation complete after 24s [id=1fccb0d2-b3ba-40ce-8505-b4d548f525f5]
grid_deployment.d1: Creating...
grid_deployment.d1: Still creating... [10s elapsed]
╷
│ Error: failed to deploy deployments: error waiting deployment: workload 0 failed within deployment 1414 with error failed to get deployment contract: contract not found: object not found; failed to revert deployments: failed to delete deployment: failed to cancel contract: failed to submit extrinsic: Priority is too low: (302980000 vs 302300000); try again
```

After trying again: terraform apply -parallelism=1 -auto-approve

```
grid_deployment.d1: Creating...
╷
│ Error: failed to create contract: ContractIsNotUnique
```

Then: terraform destroy -parallelism=1 -auto-approve

```
grid_network.net1: Destroying... [id=1fccb0d2-b3ba-40ce-8505-b4d548f525f5]
grid_network.net1: Destruction complete after 8s

Destroy complete! Resources: 1 destroyed.
```

After: terraform apply -parallelism=1 -auto-approve

```
grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
grid_network.net1: Creation complete after 16s [id=dbad6bae-b146-4f19-b1ae-8092c56f0c48]
grid_deployment.d1: Creating...
╷
│ Error: failed to create contract: ContractIsNotUnique
```

**Comment by OmarElawady** [comment]
The contract was created but zos node doesn't find it and that's why the deployment fails. I suspect it's caused by [this](https://github.com/threefoldtech/zos/issues/1696). The `priority too low` happens when two transactions are submitted concurrently from the same account. I tried create->delete ~20 times and it didn't fail once. So if it was used by someone else at the same time this could be the reason. The second apply failure was because the first deletion failed so the contract got leaked, you have to remove it manually on polkadot.

**Comment by OmarElawady** [comment]
Please reopen if it reoccurs and only one accounts is using it

**Comment by rcmorano** [comment]
JFTR, I've just faced this while creating deployments using terraform's count (which I guess could be the problem) instead of multiple `vms` blocks within the deploy resource:

`│ Error: failed to create contract: failed to create contract: failed to submit extrinsic: Priority is too low: (302980000 vs 302980000)`

**Comment by scottyeager** [comment]
I also saw this error when attempting to destroy the QSFS example deployment. Retrying succeeded.

**Comment by ashraffouda** [comment]
as mentioned in this comment https://github.com/threefoldtech/terraform-provider-grid/issues/235#issuecomment-1125182137
we have an [issue](https://github.com/threefoldtech/terraform-provider-grid/issues/393) to investigate how to do concurrent deployments but for now we should pass `-parallelism=1 #` as described [here](https://github.com/threefoldtech/terraform-provider-grid#using-the-provider)
