### ISSUE TITLE
Deploying a VM on devnet3.0 works, wirguard connection fails.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/terraform-provider-grid#26]
Depoying a vm on devnet 3.0 works, with public ip based on the example deployment `terraform` definition file:

[main-new.txt](https://github.com/threefoldtech/home/files/7121098/main-new.txt)

Public IP: works - ping + ssh
Yggdrasil IP: works - ping + ssh
Wireguard config: fails - ping + ssh

```
[Interface]
Address = 100.64.1.2
PrivateKey = CPlxEo3pHhSb9eR47L8M9XP5QZiyn+SXeH03fml2AmI=
[Peer]
PublicKey = yY08nC3pdLLd5WaIJzoOIQ3m9kuINbF9oV8BN0YSzn4=
AllowedIPs = 10.1.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 192.168.123.50:4728
```

**Comment by OmarElawady** [comment]
Node 25 has a local ip configured as a public interface ip (mine for testing). The plugin tries to search for a node with public config if it doesn't find any in the nodes specified in the terraform file (which is the case here) to install wireguard but doesn't validate that the ip is public. Will add some validation for the node config, and for now you can manually add 2 (a true public node) to the node list and it will be used for wireguard.

**Comment by OmarElawady** [comment]
Updated in the 0.1.1 released to check for the node interface before using it. Retrying your terraform setup shouldn't fail with this error.
