### ISSUE TITLE
Wireguard config changes after extending existing deployment

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/terraform-provider-grid#262]
### Terraform Version
Terraform v1.2.2
on linux_amd64
provider registry.terraform.io/threefoldtech/grid v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- wg_config

### Terraform Configuration Files
https://gist.github.com/coesensbert/30eb320e8b6d49f7fc29be7a6d8cb448

### Expected Behavior
Deploy a new vm and modify the grid network config, don't change the wireguard config that already existed

### Actual Behavior
Every time a vm is added to an existing deployment, a different public node is chosen for the wireguard endpoint.

5 vm's:

```
[Interface]
Address = 100.64.41.2
PrivateKey = GMR3yW..=
[Peer]
PublicKey = 22WfDGFjFwVtIfXQ4q..=
AllowedIPs = 10.41.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 45.156.243.244:5154

6 vm's:

[Interface]
Address = 100.64.41.2
PrivateKey = GMR3yWY..=
[Peer]
PublicKey = 2qnIj5ctOtBhgqY6HaR..=
AllowedIPs = 10.41.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 45.156.243.246:3246

7 vm's:

[Interface]
Address = 100.64.41.2
PrivateKey = GMR3yWYp..=
[Peer]
PublicKey = tB/EzOAYTDpU4+..=
AllowedIPs = 10.41.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 45.156.243.242:3492
```

### Steps to Reproduce
1. deploy a network and vm, enable wireguard for the network
2. keep the wireguard config after deploy
3. extend the deployment with another vm on a different zos node
4. compare the new wireguard config with the first one

**Comment by OmarElawady** [comment]
Fixed in https://github.com/threefoldtech/terraform-provider-grid/pull/267
