### ISSUE TITLE
Terraform deployment error - failed to submit extrinsic: Invalid Transaction

### ISSUE THREAD

**Issue by luisanadal** [threefoldtech/terraform-provider-grid#266]
Hi,
Sometimes i get the below error error, forcing me to re-apply terraform, if I  execute again "terraform applyr" then it normally works, so it looks like the error is random.

│ Error: failed to create contract: failed to create contract: failed to submit extrinsic: Invalid Transaction
│ 
│   with grid_deployment.k8s_d1,
│   on threefold-k8s.tf line 34, in resource "grid_deployment" "k8s_d1":
│   34: resource "grid_deployment" "k8s_d1" {

Using:
terraform v1.2.1

Best regards

**Comment by OmarElawady** [comment]
My only encounter with this is when the account used doesn't have enough money in it. But since retrying work, it seems to be something else.

@DylanVerstraete any idea what other reasons can cause this?

**Comment by OmarElawady** [comment]
Can you please share a `main.tf` file (with secrets redacted) on which this happens? And what network (dev/test/main) does this happen? Aand what is the plugin version? (make sure to update to latest)
