### ISSUE TITLE
Scripts using unofficial images

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#269]
### Description

Some of the scripts in [/examples/resources ](https://github.com/threefoldtech/terraform-provider-grid/tree/development/examples/resources)are using unofficial images.

### [cosmosvalidator/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/cosmosvalidator/main.tf#L25)
   - flist = "https://hub.grid.tf/ashraf.3bot/ashraffouda-threefold_hub-latest.flist" 
   
### [expose-vm/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/expose-vm/main.tf#L34)
   - flist = "https://hub.grid.tf/ashraf.3bot/strm-helloworld-http-latest.flist" 

### [external_provisioner/remote-exec-file_swarm-cluster/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/external_provisioner/remote-exec-file_swarm-cluster/main.tf#L27#L39)
   -  flist = "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04_debug-latest.flist"
   
### [external_provisioner/remote-exec_hello-world/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/external_provisioner/remote-exec_hello-world/main.tf#L26)
   -  flist = "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04-latest.flist"
   
### [external_provisioner/remote-local-exec_swarm-cluster/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/external_provisioner/remote-local-exec_swarm-cluster/main.tf#L26#L38)
   -  flist = "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04_debug-latest.flist"
   
### [mattermost/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/mattermost/main.tf#L34)
   -  flist = "https://hub.grid.tf/ashraf.3bot/ashraffouda-mattermost-latest.flist"
   
### [peertube/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/peertube/main.tf#L34)
   -  flist = "https://hub.grid.tf/omarabdul3ziz.3bot/threefoldtech-peertube-v3.0.2.flist"
   
### [presearch/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/presearch/main.tf#L34)
   - flist = "https://hub.grid.tf/omarabdul3ziz.3bot/omarabdul3ziz-presearch-v2.2.flist"
   
### [simple-dynamic/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/simple-dynamic/main.tf#L51)
   - flist = "https://hub.grid.tf/omar0.3bot/omarelawady-simple-http-server-latest.flist"
   
### [taiga/main.tf](https://github.com/threefoldtech/terraform-provider-grid/blob/development/examples/resources/taiga/main.tf#L32)
   - flist = "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_taiga_docker-latest.flist"

**Comment by AhmedHanafy725** [comment]
check the official flist urls here https://github.com/threefoldtech/grid_weblets/issues/808#issuecomment-1156238283

**Comment by MarioBassem** [comment]
@AhmedHanafy725 some of the flists in the examples are not listed in https://github.com/threefoldtech/grid_weblets/issues/808#issuecomment-1156238283

1. expose vm: "https://hub.grid.tf/ashraf.3bot/strm-helloworld-http-latest.flist"
2. cosmosvalidator: "https://hub.grid.tf/ashraf.3bot/ashraffouda-threefold_hub-latest.flist"
3. external provisioner: "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04-latest.flist"
4. external provisioner: "https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04_debug-latest.flist"
5. simple-dynamic: "https://hub.grid.tf/omar0.3bot/omarelawady-simple-http-server-latest.flist"

**Comment by maxux** [comment]
```
ashraf.3bot/strm-helloworld-http-latest.flist -> 'tf-official-apps/strm-helloworld-http-latest.flist
ashraf.3bot/ashraffouda-threefold_hub-latest.flist -> tf-official-apps/threefold_hub-latest.flist
samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04-latest.flist -> tf-official-apps/grid3_ubuntu20.04-latest.flist
samehabouelsaad.3bot/abouelsaad-grid3_ubuntu20.04_debug-latest.flist -> tf-official-apps/grid3_ubuntu20.04_debug-latest.flist
omar0.3bot/omarelawady-simple-http-server-latest.flist -> tf-official-apps/simple-http-server-latest.flist
```
