### ISSUE TITLE
Modify the IP range in some scripts

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#287]
### Description

Some of the scripts (`expose-vm`, `peertube`) have incorrect iprange subnet and when you try to deploy them with the same config in the main.tf file they produce this error.

```
╷
│ Error: subnet in iprange 10.1.0.0/24 should be 16
│ 
│   with grid_network.net1,
│   on main.tf line 21, in resource "grid_network" "net1":
│   21: resource "grid_network" "net1" {
│ 
╵
```

and when the value is changed from `24` to `16` they get deployed without any issues.

### Steps to Reproduce

- Clone and install [terraform-provider-grid](https://github.com/threefoldtech/terraform-provider-grid).
- Navigate to `examples/resources/expose-vm/main.tf`
- or
- Navigate to `examples/resources/peertube/main.tf`
- add you ssh key and credentials without changing anything else in the script
- execute `terraform init && terraform apply -parallelism=1`

**Comment by MarioBassem** [comment]
ip ranges will be computed and user won't be providing them as in (https://github.com/threefoldtech/terraform-provider-grid/pull/361)
examples are updated here (https://github.com/threefoldtech/terraform-provider-grid/pull/362) and will be released in v1.5.9
