### ISSUE TITLE
Resource validation happens after the network is deployed

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#288]
### Description

Resource validation happens after the network is deployed so in many cases the network will be deployed then the deployment will fail.

some of these cases are: 

 - Insufficient resources on the mentioned node.
 - Invalid inputs like ( cpu = 1000 or disk size = 99999999 , etc... ) 

   ![image](https://user-images.githubusercontent.com/101194226/177044434-6ca97d4e-f254-4736-978d-2d1aee921068.png)

   as it can be seen here the network was deployed before checking if the cpu input was valid and then the deployment failed.

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
grid_network.net1: Still creating... [20s elapsed]
grid_network.net1: Still creating... [30s elapsed]
grid_network.net1: Still creating... [40s elapsed]
grid_network.net1: Creation complete after 49s [id=58abcb11-f344-449c-981d-b315feee87f5]
grid_deployment.d1: Creating...
grid_deployment.d1: Still creating... [10s elapsed]
grid_deployment.d1: Still creating... [20s elapsed]
╷
│ Error: error waiting deployment: workload vm1 within deployment 8677 failed with error: machine configuration validation failed: invalid cpu must be between 1 and 32
│ 
│   with grid_deployment.d1,
│   on main.tf line 19, in resource "grid_deployment" "d1":
│   19: resource "grid_deployment" "d1" {
│ 
╵
```
   same happens in memory and disk

   ![image](https://user-images.githubusercontent.com/101194226/177044873-42ea51e6-7a15-476e-b463-ac664a3cef8e.png)

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

grid_network.net1: Creating...
grid_network.net1: Still creating... [10s elapsed]
grid_network.net1: Still creating... [20s elapsed]
grid_network.net1: Still creating... [30s elapsed]
grid_network.net1: Still creating... [40s elapsed]
grid_network.net1: Still creating... [50s elapsed]
grid_network.net1: Creation complete after 51s [id=ec988b55-b58a-4e8f-a845-07906e8d0256]
grid_deployment.d1: Creating...
╷
│ Error: node 8 doesn't have enough resources. needed: [mru: 1048575998951424, sru: 2147483648, hru: 0], free: [mru: 182522610893, sru: 916846198784, hru: 6001185964032]
│ 
│   with grid_deployment.d1,
│   on main.tf line 19, in resource "grid_deployment" "d1":
│   19: resource "grid_deployment" "d1" {
│ 
╵
````

### Suggestions 

i think it would be better and more efficient to add instant validation for inputs like 
CPU: (1 -> 32)
Memory: (256 -> 262144)
Disk: (1 -> 10000)
and validate these input before the apply phase (if possible)

and for valid input but insufficient node resources the validation for these inputs should be done before deploying the network (again if possible)

**Comment by ashraffouda** [comment]
we now have the scheduler, so if the user wants a node that is satisfying his request he would use it, otherwise if he decided to use a node directly he should make sure it is sufficient to his request

**Comment by ashraffouda** [comment]
> we now have the scheduler, so if the user wants a node that is satisfying his request he would use it, otherwise if he decided to use a node directly he should make sure it is sufficient to his request

@xmonader what do u think?

**Comment by ashraffouda** [comment]
we will do some validation steps described in this issue https://github.com/threefoldtech/terraform-provider-grid/issues/671
and as mentioned in 

> we now have the scheduler, so if the user wants a node that is satisfying his request he would use it, otherwise if he decided to use a node directly he should make sure it is sufficient to his request

if the user explicitly specifies a node he should make sure that it has enough resources or his deployment will fail
