### ISSUE TITLE
Can Deploy Presearch without a PRESEARCH_REGISTRATION_CODE using terraform

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#320]
### presearch deployment success without inserting a PRESEARCH_REGISTRATION_CODE using terraform
steps made to test this case

1. using terrafrom go to examples/resources/presearch
2. insert your ssh and disk deployments info and nodes
3. [run command](run: terraform init && terraform apply -parallelism=1) in your terminal
4. the machine is up and you can ssh on it without a presearch node attached
![Screenshot from 2022-09-21 17-55-03](https://user-images.githubusercontent.com/110984055/191554121-bd515e7f-5fb8-4fec-a001-1447fdfd5ead.png)
![Screenshot from 2022-09-21 17-56-01](https://user-images.githubusercontent.com/110984055/191554115-e305d993-381f-429e-b1a2-7d80d7a2504d.png)

**Comment by ramezsaeed** [comment]
in this case it will act like a normal VM, and its a user responsibility to provide the reg code
