### ISSUE TITLE
Unclear error message while deploying on a rented node

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#346]
### Description

The error message for deployment on a rented node needs to updated/more clear, while testing i tried to deploy on a node that's rented by another twin but instead of getting a clear error message that this node is rented by another user or already has a rent contract i got this message which doesn't clarify where the problem/issue is coming from.

```
╷
│ Error: failed to create contract: contract not found: object not found
│ 
│   with grid_network.net1,
│   on main.tf line 12, in resource "grid_network" "net1":
│   12: resource "grid_network" "net1" {
│ 
╵
```
![image](https://user-images.githubusercontent.com/101194226/200300399-1131b4c6-3ae9-4393-b6cb-4660aa697a63.png)

### Terraform Version

- Terraform v1.1.7
- Terrafrom gird provider v1.5.8
- Network: mainnet.

### Terraform Configuration Files

- Any of these [scripts](https://github.com/threefoldtech/terraform-provider-grid/tree/development/examples/resources).

### Expected Behavior

- The deployment should fail with a clear error message.

### Actual Behavior

- The deployment failed with an ambiguous message. 

### Steps to Reproduce

- Rent any node from the dashboard.
- From another twin try to deploy anything on the rented node using any of these [scripts](https://github.com/threefoldtech/terraform-provider-grid/tree/development/examples/resources).
- Wait for the deployment to fail.

**Comment by xmonader** [comment]
has to go to next

**Comment by MarioBassem** [comment]
Solved here (https://github.com/threefoldtech/terraform-provider-grid/pull/522)
Now if a user tried to deploy on a rented node, this error will return:
`failed to create contract: NodeHasRentContract`

**Comment by A-Harby** [comment]
I tried with node 12 and 21 which are both rented by a different twin.
![image](https://user-images.githubusercontent.com/109473873/230887009-ea88017f-6f6d-4e05-8643-fa6ea0e8a0fb.png)

![image](https://user-images.githubusercontent.com/109473873/230887098-08dfaf8a-b12f-40eb-9b89-bb9b2f12ae68.png)
But I got a different error saying `failed to create contract: NodeIsNotDedicated`.
![image](https://user-images.githubusercontent.com/109473873/230886871-5b93f7e3-9aef-442b-a8d4-af4d20332a52.png)

**Comment by MarioBassem** [comment]
for some reason, now this is the error coming from the chain when trying to deploy on a node with a rent contract.
i opened an issue on the tfchain (https://github.com/threefoldtech/tfchain/issues/682)

**Comment by khaledyoussef24** [comment]
verfied deployed on reserved node.
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/d07baeda-dce6-44ad-b709-243b5eaa2ce4)
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/c5f205d4-f320-4af3-8fac-5bb75e85a5c4)
