### ISSUE TITLE
convert VMs to a map instead of a list 

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/terraform-provider-grid#350]
Currently, if a user wanted to delete or create a new vm, they have to do that from the end of the vms list in the main.tf file.
Since terraform recognizes the vms as a list, if the order changes, the vms state becomes unclean.

since vms should not be identified by their order, shcema.TypeSet or schema.TypeMap should be used instead of shcema.TypeList for vms.

**Comment by ashraffouda** [comment]
duplicate of https://github.com/threefoldtech/terraform-provider-grid/issues/586#issuecomment-1592445140
