### ISSUE TITLE
wireguard config disappears if all nodes are publicly accessible 

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/terraform-provider-grid#353]
if after an update in network resource, all nodes were found to be publicly accessible, the provider remove the wireguard configuration output.

**Comment by coesensbert** [comment]
Is there a way to have a quick fix for ops?
We use the wg config to reach the internal subnet of 7 vm's in a deployment for monitoring, which is currently down. These are 6 public nodes in production for mainnet, and [one graphql stack](https://github.com/threefoldtech/tf_operations/issues/1253)

**Comment by MarioBassem** [comment]
> Is there a way to have a quick fix for ops? We use the wg config to reach the internal subnet of 7 vm's in a deployment for monitoring, which is currently down. These are 6 public nodes in production for mainnet, and [one graphql stack](https://github.com/threefoldtech/tf_operations/issues/1253)

will prepare a pr today fixing this (hopefully :D)
