### ISSUE TITLE
update provider docs

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/terraform-provider-grid#367]
provider docs are outdated and changes in the resources schema are no longer reflected in the docs.
After every change in the resources schema, docs should be regenerated.
a package like [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) could be used.

**Comment by MarioBassem** [comment]
updated here (https://github.com/threefoldtech/terraform-provider-grid/commit/953725c2d9fe3ec1bcd0bf5dab11de7cec8c453d)

**Comment by xmonader** [comment]
no, this is not enough. the linked PR is only for documentation, lint and test targets
this issue is about expanding the provider documentation

**Comment by ashraffouda** [comment]
already done
