### ISSUE TITLE
terraform tests fails

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#368]
terraform tests fails giving different errors due to the lattes version update

terratests daily work flows fail

![Screenshot from 2022-11-23 17-27-33](https://user-images.githubusercontent.com/110984055/203585137-31927667-4494-40a6-b52e-20aac6c982c7.png)

automated terra tests needs to be updated

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/terraform-provider-grid/issues/389
