### ISSUE TITLE
Create github workflow to support different nets(dev, test, main)

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#372]
now we are depending on subpackages to manage changes between different networks, but now we have changes in the provider itself. which will lead to unstable behavior dealing with different networks. so what we are planning to do is to have a branch for each network and a corresponding github workflow for each branch to release a provider suitable for that network only
so will be something like that 
terraform-provider-grid-dev
terraform-provider-grid-test
terraform-provider-grid-qa
terraform-provider-grid-main

**Comment by xmonader** [comment]
I don't think there's a way around this :(

**Comment by ashraffouda** [comment]
this will be managed by versions, examples refelect each net
