### ISSUE TITLE
update examples for 3.8

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/terraform-provider-grid#376]
update the following examples to reflect 3.8 changes

- [ ] single vm
- [ ] multiple vms
- [ ] kubernetes
- [ ] mounts
- [ ] qsfs
- [ ] mattermost
- [ ] peertube
- [ ] caprover
- [ ] provisioners
- [ ] taiga
- [ ] gateway name
- [ ] gateway fqdn

**Comment by MarioBassem** [comment]
all examples were updated for latest release.
only one that is not available is caprover.
