### ISSUE TITLE
investigate whether provider could wait for deployments concurrently.

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/terraform-provider-grid#393]
Currently, resources like network and kubernetes wait sequentially for a deployment to be deployed on a node. 
And although chain transactions could only happen sequentially for now, the provider doesn't have to wait for every deployment to be deployed on a node.
So, could deployment creations and updates be done sequentially, and then let the provider wait for all deployments to be deployed concurrently?

**Comment by ashraffouda** [comment]
duplicate of https://github.com/threefoldtech/terraform-provider-grid/issues/12
