### ISSUE TITLE
explain the minimum TFTs you need to make a deployment 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/terraform-provider-grid#40]
need more explain the amount of TFT for every deployment 
for example if a user need to deploy a zdb with size 10G what is the TFT needed for make this deployment 

how to know resource units(CRU, MRU, NRU etc ....) ?

**Comment by xmonader** [comment]
https://info.threefold.io/#/threefold__grid_pricing?id=cloud-unit-pricing
https://info.threefold.io/#/threefold__resource_units
https://github.com/threefoldtech/tfchain/issues/25#issuecomment-892746866
