### ISSUE TITLE
failed to deploy deployments: error waiting deployment: workload "T" state within deployment N is paused

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/terraform-provider-grid#403]
I get the following error, if I want to apply something to the grid via terraform. I get this since around 3 days. The deployment 15145 and 15146 is up and running and i can ping them...

Provider version 1.6.2

**Errormessage:**
╷
│ Error: failed to deploy deployments: error waiting deployment: workload SlaveOfDoom01 state within deployment 15145 is paused: paused; failed to revert deployments: error waiting deployment: workload SlaveOfDoom03 state within deployment 15146 is paused: paused; try again
│ 
│   with module.kubernetes.grid_kubernetes.k8s1,
│   on ../../modules/threefold/main.tf line 50, in resource "grid_kubernetes" "k8s1":
│   50: resource "grid_kubernetes" "k8s1" {
│ 
╵

**Playground:**
ID | Type | Node ID | State | Billing Rate | Solution type | Solution name | Created at | Expiration | Actions
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 15145 | node | 31 | Created | 5.0758749 TFT/hour | kubernetes |   | 3.12.2022, 14:20:54 | - | Show Details
  | 15146 | node | 34 | Created | 5.0712312 TFT/hour | kubernetes |   | 3.12.2022, 14:21:12 | -

**Comment by MarioBassem** [comment]
the error indicates that the `slaveOfDoom3` workload is in paused state, which means that this account has no enough tokens to keep billing for this workload, and the wallet needs to be funded. After the wallet is refunded, the paused workload should return to a stateOK within an hour.
If this is not the case, please report it.

**Comment by fl0wm0ti0n** [comment]
thanks for your informations, i have to say in this time i had enought tokens a few days and the error didnt get away. maybe there is a time/performance issue. i can test it again if you want.

1. set up the deployments
2. let run out the tokens
3. wait for the error
4. fill up tokens
5. wait
6. try to change deployments.
