### ISSUE TITLE
Gateway FQDN integration tests

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/terraform-provider-grid#419]
running the integration tests currently fails with this error:
```
Error:          Received unexpected error:
                                FatalError{Underlying: error while running command: exit status 1; ╷
                                │ Error: couldn't get node 1 client: failed to get node: object not found
                                │ 
                                │   with grid_fqdn_proxy.p1,
                                │   on main.tf line 20, in resource "grid_fqdn_proxy" "p1":
                                │   20: resource "grid_fqdn_proxy" "p1" {
                                │ 
                                ╵}
```

also the test uses ping to try reaching `remote.hassan.grid.tf` if it's reachable then the test succeed, there is a problem that this FQDN is reachable without deploying the gateway so pinging it always works, maybe the test should use something other than ping?

**Comment by AbdelrahmanElawady** [comment]
the error was because i was on devnet and not testnet however the second part is still an issue because pinging the FQDN without deploying works too so the test always succeed.

**Comment by khaledyoussef24** [comment]
added a gateway tests with back end in the new integration tests to make the test more efficient
