### ISSUE TITLE
Taiga integration test

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/terraform-provider-grid#424]
this line doesn't return desired output:
`status1 = tests.Wait(webip, "22")`
as it's trying to dial `webip` at port 22 it keeps failing and retrying for 3 minutes and it fails but it returns true anyway.

trying to access `webip` outputs `Bad Gateway` so pinging `webip` returns that it's reachable however it's not running properly

and pinging `webip` `grid3taiga.gent02.test.grid.tf` without deploying works fine so that check doesn't affect the test:
```
out1, _ := exec.Command("ping", webip, "-c 5", "-i 3", "-w 10").Output()
assert.NotContains(t, string(out1), "Destination Host Unreachable")
```

**Comment by khaledyoussef24** [comment]
changed the function name and it now uses tcp instead of ping to be more efficient
