### ISSUE TITLE
investigate other ways to convert schemas

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/terraform-provider-grid#426]
currently, converting between go structs and terraform's resourceData (map[string]interface{}) is done manually in the provider, while some already tested packages offer this functionality.
- struct to map[string]interface{} : https://github.com/fatih/structs
- map[string]interface{} to struct: https://github.com/mitchellh/mapstructure

**Comment by MarioBassem** [comment]
the packages mentioned are made for general use and eventually may not be useful in our case.
maybe a new package needs to be developed to specifically get and set information from terraform resourceData maps.

**Comment by ashraffouda** [comment]
duplicate of https://github.com/threefoldtech/terraform-provider-grid/issues/258
