### ISSUE TITLE
unify output variable naming case

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/terraform-provider-grid#432]
![image](https://user-images.githubusercontent.com/64129/209463181-747f6665-a2d5-4bdd-a59f-3d2563af4999.png)

there's computedip and ygg_ip, let's make sure there's a consistent naming and i'm also against mentioning ygg_ip as we mention `planetary` all over the place

**Comment by rawdaGastan** [comment]
there is another planetary field which enables Yggdrasil allocation
