### ISSUE TITLE
network_state review

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/terraform-provider-grid#437]
![image](https://user-images.githubusercontent.com/64129/209579253-d2190675-488e-4753-9cd9-5b0ce79d26e5.png)
Need to use a better name, I believe even NetworkMap is a bettername, if we must create a type definition, also there's no reason not to export it?

![image](https://user-images.githubusercontent.com/64129/209579405-738d7c7f-3c6e-4eb3-a9ad-7c0de402aa33.png)

inconsistently, we have this NodeIPs exported, and deploymentIps unexported, also is it a node to IP or a node to multiple IPs?

![image](https://user-images.githubusercontent.com/64129/209579450-c6477852-518d-4d52-ab4b-4f1845b6f696.png)

Linter should have complained about having a factory function for an unexported type?

![image](https://user-images.githubusercontent.com/64129/209579510-938d345b-6079-4b7d-929b-876db9bb62e1.png)
GetNetwork returns an `Interface` Network, which I argue we don't really need it you should use a concrete type, also returning an interface in general from functions, well maybe except for the `error` interface is redflag, let aside that you're also returning a pointer to `network`

![image](https://user-images.githubusercontent.com/64129/209579714-4d095596-a777-4bf0-b9e4-bee8869f7014.png)
why didn't we not return `n.NodeIPs[nodeID]` directly ?

![image](https://user-images.githubusercontent.com/64129/209579826-5067d2b3-8a32-431b-9786-447f9df968bc.png)

you can safely call delete on an uninitialized map

also, all of the exported functions need to have proper comments , and a package comment as well https://tip.golang.org/doc/comment

**Comment by rawdaGastan** [comment]
why didn't we not return n.NodeIPs[nodeID] directly ?

- because we need the ips of the deployments

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/210670161-524d266f-c437-466a-b924-a61c3cee7179.png)


for readability and correctness, lets 
- replace deploymentIPs with deploymentHostIDs as it's a map from deployment to reserved host IDs
- replace NodeIPs, to NodeDeploymentHostIDs map

should reflect also in the remaining functions to denote it's a HostID not an IP, maybe we can add IPs based on the subnet, but never treat the hostID as an IP
