### ISSUE TITLE
QSFS example -  mount is not not a valid disk workload

### ISSUE THREAD

**Issue by Nelson361** [threefoldtech/terraform-provider-grid#499]
The QSFS example works fine, but seemingly only with the .flist included in the example. This flist is a very basic arch which isn't very useful. Tried several others from the hub and all give this error.

 Error: error waiting deployment: workload vm within deployment 14342 failed with error: mount is not not a valid disk workload
│
│   with grid_deployment.qsfs,
│   on main.tf line 67, in resource "grid_deployment" "qsfs":
│   67: resource "grid_deployment" "qsfs" {

**Comment by MarioBassem** [comment]
Sorry for the late reply. 
I tried to reproduce the issue but had no luck.
I also tried to deploy a QSFS using different flists and they all worked fine.
Can you provide the main.tf you used for this deployment?
