### ISSUE TITLE
Tests should use scheduler to get online nodes with free resources

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#511]
In integration tests for example, nodes ids are hard coded in the tests while some nodes maybe offline, not ready or don't have enough resources . this should be automated somehow using the scheduler or checking which nodes are ready and have enough resources at the beginning of the tests

**Comment by khaledyoussef24** [comment]
verified in most of the tests and working fine
![image](https://user-images.githubusercontent.com/110984055/220574474-d5ed35a1-2ce9-4e58-bffc-7695085bda60.png)
![image](https://user-images.githubusercontent.com/110984055/220574519-cdb39a30-dd78-4b40-87ed-4d80276d9b48.png)
![image](https://user-images.githubusercontent.com/110984055/220578398-146e8590-672a-4a59-8fb7-897b088c5e00.png)
![image](https://user-images.githubusercontent.com/110984055/220580633-88df1ad6-e325-4487-b05a-8d4a1f90eb0c.png)
 except single vm tests
![image](https://user-images.githubusercontent.com/110984055/220582467-94db40b2-b6fa-44d3-a608-15bf6fd4a6b1.png)

**Comment by ashraffouda** [comment]
done here https://github.com/threefoldtech/terraform-provider-grid/pull/539
