### ISSUE TITLE
New version v1.6.4 causing error 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/terraform-provider-grid#518]
New version v1.6.4 cause a error preventing all the scripts from running.

`Error: couldn't get node 3 client: failed to get node: failed to load object: type *substrate.Node does not support Decodeable interface and could not be decoded field by field, error: expected more bytes, but could not decode any more`

![image](https://user-images.githubusercontent.com/109473873/215329359-0b31ad35-67a3-49d7-a4a6-f123b849f0f9.png)

Old version v1.6.3 works fine.

To track issue (or which version to be the default).

**Comment by ashraffouda** [comment]
Now we have a provider version for each network
latest now on qa is 1.7.1-qa

https://github.com/threefoldtech/terraform-provider-grid/blob/development_docs_update/README.md#latest-releases

**Comment by A-Harby** [comment]
Verified on Qanet, v1.7.1-qa.
I was able to change Verso in to specified one for qa v1.7.1 as in [docs](https://github.com/threefoldtech/terraform-provider-grid/blob/750bd36a4f687eed2db23212fea068de93ba55d9/wiki/usage.md).
![image](https://user-images.githubusercontent.com/109473873/215771989-c3dc85fa-aea8-496a-874f-cb8572e57d2e.png)
And was able to deploy a VM sucessfully.
![image](https://user-images.githubusercontent.com/109473873/215772179-a9739323-3672-495b-9138-9369094c3432.png)
