### ISSUE TITLE
can not deploy using terraform on testnet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#530]
### Terraform  version = "1.7.1-rc1"

trying to deploy  different deployments on terraform gets  errors even if the nodes are up

![Screenshot from 2023-02-06 08-23-47](https://user-images.githubusercontent.com/110984055/216907061-275e247a-43ce-4c7d-b1a4-9b864dce5537.png)
![image](https://user-images.githubusercontent.com/110984055/216907100-38159ea7-1631-4c52-96c4-dc64eb248399.png)

**Comment by khaledyoussef24** [comment]
the capacity filter on weblets selected to deploy on node 3 and deployed successfully
![image](https://user-images.githubusercontent.com/110984055/216910755-176168b1-ebac-4ec0-b001-5d900f65ed88.png)

but when tried to deploy on the same node from terraform got the same error
![image](https://user-images.githubusercontent.com/110984055/216910651-f8452725-140a-4f65-ab46-7dd458e8782d.png)

**Comment by ashraffouda** [comment]
can not reproduce
