### ISSUE TITLE
Add validation to required environment variables

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/terraform-provider-grid#538]
## Is your feature request related to a problem? Please describe

It seems that there is an expectation that there should be some validation to certain environment variables that are required for certain deployments to function properly. See [here](https://app.testlodge.com/a/26076/projects/40893/suites/193850)

Examples for that include resources like:
- Taiga: Needing admin username and password
- Presearch: Needing registration key

**Comment by ashraffouda** [comment]
those are just examples to show user how to deploy with different flist, our provider doesn't have modules for specific images this is the responsibility of the user to provide the required env varrs
