### ISSUE TITLE
can't deploy a gateway with ygg ip

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/terraform-provider-grid#54]
i deployed a VM with planetary network 
then i tried to use ygg ip as a backend for a gateway 
```
backends = [format("http://%s", trimsuffix(grid_deployment.d1.vms[0].ygg_ip, "/24"))]
```
got this error: 
```
Error: deployment is invalid: failed to validate backend '304:2777:d158:6203:f0c8:512a:f9ae:37e0': failed to parse backend: parse "304:2777:d158:6203:f0c8:512a:f9ae:37e0": first path segment in URL cannot contain colon
```

then i tried a public ip for a VM and it worked fine
![image](https://user-images.githubusercontent.com/31102305/135175296-354aadab-fab0-49b2-884c-f1f7fd56214d.png)

does backend (for gateway) support IPv6 as backend?

**Comment by OmarElawady** [comment]
it should be `http:[<ygg_ip>]:port` and the port should be optional.
