### ISSUE TITLE
remove parallelism=1 

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/terraform-provider-grid#571]
Remove parallelism=1 from: 
- docs 
- tests
- examples

**Comment by A-Harby** [comment]
Parralism=1 was removed from docs, tests and examples except for 

K8s test
![image](https://user-images.githubusercontent.com/109473873/226186883-cb687886-acd2-4441-8fbb-b343126a097e.png)

zdb test
![image](https://user-images.githubusercontent.com/109473873/226186842-935bd02e-2c31-4281-8bb7-955e3284d883.png)

**Comment by xmonader** [comment]
Fixed in https://github.com/threefoldtech/terraform-provider-grid/commit/fefc9e0b7a99988f1587e96b669fafc6effe48f1
