### ISSUE TITLE
Support gateway over wireguard

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/terraform-provider-grid#573]
## Gateway over wireguard instead of yggdrasil

Right now, gateways uses an `ygg` ip. Which is not reliable as it should. Instead you need to use new support for gateway to gateway traffic over user private  wireguard network.

## Use the new `network` flag on the gw workload
New attribute is available on all `gateway` workloads `network` (optional) which once provided the gateway will then join the user network. This will allow the backend to be a `private` ip of a private workload that is part of the same network as the gateways.

This can happen as follows:
- User add the gateway to his network. Note that gateways always has `public-config` so they can also be used as wireguard access points. 
- A gateway workload (named, or fqdn gw workload) then can be given 
  - name of the user network (the one that was deployed on the gateway node)
  - backend in the form of `http://<private-ip>:port` of where the traffic should be gatewayed to. The private Ip is the ip of any vm that is reachable over that network.
  - backend also can be of the form `<private-ip>:port` in case of tls-passthrough.

**Comment by muhamadazmy** [comment]
Please check the zos changes to the gateway types. Those changes are only available on devnet right now. Please make sure all gateway features are working as expected, if not feel free to create issues on zos.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Firstly i deployed a vm with the and ran a simple python http server on it.

Then i deployed a name gateway and passed the same network name to it via the new `network` parameter and used the private ip of the vm to deploy it. and the gateway was deployed on the same gateway node where the node had its wireguard config added.

and the gateway was successfully deployed and worked without any issues.

![image](https://github.com/threefoldtech/terraform-provider-grid/assets/101194226/d7d4a527-bd8f-40da-a861-541433818ae8)

![image](https://github.com/threefoldtech/terraform-provider-grid/assets/101194226/de3fe6a4-c23a-41be-bf6b-5184bc4940a2)

![image](https://github.com/threefoldtech/terraform-provider-grid/assets/101194226/fd78e386-ca2f-40bc-ad96-7fcbea9dc1f6)
