### ISSUE TITLE
Update ssh key setting in k8s example

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#588]
### Description

The K8s example needs to be updated to retrieve the public ssh key automatically from `~/.ssh/id_rsa.pub` like the updated examples instead of adding it manually.

![image](https://user-images.githubusercontent.com/101194226/228202115-565095bc-ecc4-4148-8c41-e1d2d90cd9e5.png)

It would also be great if it could be updated in the rest of the examples if there are other ones that are still using the old method.

**Comment by ashraffouda** [comment]
updated, also other examples that uses ssh_key updated https://github.com/threefoldtech/terraform-provider-grid/pull/590
