### ISSUE TITLE
make integration for terratests keeps failing 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#634]
### after running make integration to run all the terraform tests alll of them expcept some tests are failed

many of them due to the version in the `main.tf` files
![image](https://github.com/threefoldtech/test_feedback/assets/110984055/e94e7391-34f7-4ec3-853b-fdf124a2ef19)
other tests may fail due to grid proxy node filter
![Screenshot from 2023-05-14 11-46-04](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/658056ab-deeb-4d1a-b722-8167fa0b0083)

the tests should be running on the current version and should pass

**Comment by xmonader** [comment]
The agreed on workflow is

1- against all commits we run the unittest suite
2- nightly runs the following
	- full integration tests against devnet environment from development branch
	- full integration tests against testnet, mainnet environment from the latest version (this is needed even after releases in case of hotfixes being applied on testnet/mainnet environments)

**Comment by ashraffouda** [comment]
do we need also to run this integration test right after releases to different networks? 
for example when we release 2.0.0-rc to run them against test net?

**Comment by khaledyoussef24** [comment]
scenarios are done.
opening another issues for tests which are failing.
