### ISSUE TITLE
create docker image for terraform to use in running tests

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#657]
sometimes we need to run terraform tests outside of the workflow like to test before release
running tests locally is not always good because wireguard is not working in egypt for example. this will make tests to fail
running on a remote machine is a good idea but this requires to install a lot dependecies , so having a ready docker image will make it much easier

**Comment by khaledyoussef24** [comment]
moving this issue to 3.12

**Comment by muhamadazmy** [comment]
Any updates?

**Comment by khaledyoussef24** [comment]
should we start the tests on the container or just install the dependencies to make it ready to start the testing  manually ?

**Comment by khaledyoussef24** [comment]
docker image and flist made for the terraform testing and working fine
docker image:
https://hub.docker.com/r/khaledgx96/terraform_testing
flist:
https://hub.grid.tf/khaledyoussef.3bot/khaledgx96-terraform_testing-latest.flist
