### ISSUE TITLE
fix broken integration tests

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#658]
now we have those tests broken, please make sure they are working fine 
1- TestGateWayPrivate this test is written with domain hardcoded points to devnet and nightly tests are running on qa 
2- qsfs
3- k8s with modules

**Comment by khaledyoussef24** [comment]
Qsfs 
k8s with module
K8s function
Gateway tests
Taiga

**Comment by khaledyoussef24** [comment]
some of integrations tests are failing:

Qsfs
k8s with module
K8s function
Gateway tests
Taiga
and also there is another issue in the workflow it fails due time out after 10 minutes

**Comment by khaledyoussef24** [comment]
working on comments on the pr

**Comment by xmonader** [comment]
@khaledyoussef24 status?

**Comment by khaledyoussef24** [comment]
k8s using module
wireguard are the only tests are failing now
