### ISSUE TITLE
terraform GPU support

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/terraform-provider-grid#660]
https://github.com/threefoldtech/home/issues/1392 

https://github.com/threefoldtech/zos/pull/1973

**Comment by ashraffouda** [comment]
changes needed to integrate GPU changes
1- change scheduler to filter out nodes with has_gpu option
2- change vms schema in resource_deployment to accept GPU (list of GPU ids that will be used by the vm)
3- add listGPU method to the tfgrid_sdk_go in grid_client node.go
4- change node schema to include has_gpu and extra_fees in grid_proxy

**Comment by ashraffouda** [comment]
gpu support added here  https://github.com/threefoldtech/terraform-provider-grid/pull/684

**Comment by A-Harby** [comment]
Verified on Development_2.0.0
Vm was successfully deployed 
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/109473873/f8bb3cee-3bd8-46cc-be65-40c6a6bb1b34)
And GPU card was listed
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/109473873/2d5fbe78-f083-4737-a665-6dc3e3eba7b8)
(But I had to change flist to the Ubuntu, used is Alpine)
