### ISSUE TITLE
validate data before sending it to the node

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#671]
we need to validate the user has entered a reasonable data before sending it to the node for example 
if the user entered cpu = 100000 this should fail from the begining 
also validate that all names are in lower case

**Comment by khaledyoussef24** [comment]
verified 
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/89a197bb-da14-47bd-9926-79828d5a16a8)
