### ISSUE TITLE
make sure docs are updated in info_grid

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#672]
make sure [docs](https://github.com/threefoldtech/info_grid/tree/development/src/terraform) in info_grid are updated to the current terraform version

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/info_grid/pull/159

**Comment by khaledyoussef24** [comment]
verified hyperlinks now works fine
scheduler: 
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/36d1027c-3d83-46f9-aa56-20fb1211aff4)

[In descruibing the deployment](https://www.manual.grid.tf/terraform/resources/terraform_vm.html#describing-the-deployment)
now a link for the dashboard is added to redirect you to the dashboard
and another link for exploring the capacity for the dashboard manual both working fine
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/9bbcf1a9-e125-428c-aebb-ee0edf51aae0)

the scheduler hyper link in [find your node](https://www.manual.grid.tf/terraform/terraform_basics.html#find-your-node) works also

and scheduler guide typo also fixed
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/1c3e84c6-6b28-45cf-8557-8def0fab7749)
