### ISSUE TITLE
deploying a vm with gpu on a node that not rented should fail

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/terraform-provider-grid#685]
I tried to deploy a vm on node `93`  on devnet and the deployment done successfully without renting the node
the contract id is `31954`
![Screenshot from 2023-06-25 16-59-46](https://github.com/threefoldtech/terraform-provider-grid/assets/1689456/11091fee-de51-41e3-903f-f14621ee8637)

**Comment by ashraffouda** [comment]
related to https://github.com/threefoldtech/tfchain/issues/764

**Comment by xmonader** [comment]
Now there's a PR on tfchain to fix, closing
