### ISSUE TITLE
Unclear error message while deploying on a rented node

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/terraform-provider-grid#707]
### Description

The error message for deploying on a rented node is unclear.

```
╷
│ Error: could not deploy network mountDeployment: failed to create contract: failed to create contract: unknown module error (26) with code [25 0 0 0] occured, please create the module error list
│ 
│   with grid_network.net1,
│   on main.tf line 18, in resource "grid_network" "net1":
│   18: resource "grid_network" "net1" {
│ 
╵
```
![image](https://github.com/threefoldtech/terraform-provider-grid/assets/101194226/a236d9b9-b9eb-4348-9764-156977726eef)

### Terraform Version

```
Terraform v1.5.2
```
```
provider registry.terraform.io/threefoldtech/grid v1.9.1-dev
```

### Terraform Configuration Files

[main.tf](https://gist.github.com/mohamedamer453/0ea960f5b8bf275916cd6d6455ea134d)

### Debug Output

https://gist.github.com/mohamedamer453/ecdfd68ee289009cb094512d262d58c0

### Expected Behavior

The deployment should fail with a clear error message mentioning that the entered node is rented by another twin or not available for deployment for your twin.

### Actual Behavior

```
╷
│ Error: could not deploy network mountDeployment: failed to create contract: failed to create contract: unknown module error (26) with code [25 0 0 0] occured, please create the module error list
│ 
│   with grid_network.net1,
│   on main.tf line 18, in resource "grid_network" "net1":
│   18: resource "grid_network" "net1" {
│ 
╵
```

### Steps to Reproduce

Please list your bug environment:

1. OS: `Ubuntu 22.04`
2. NETWORK: `dev`
3. Version: `1.9.1-dev`

Please list the steps required to reproduce the issue, for example:

- [main.tf](https://gist.github.com/mohamedamer453/0ea960f5b8bf275916cd6d6455ea134d)
- Update the node id with the id of any rented node.
- `terraform init && terraform apply`

**Comment by rawdaGastan** [comment]
substrate client is updated now
