### ISSUE TITLE
public IP deployment failed but contract is still created 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#753]
###Description 
public IP deployment failed but contract is still created 
![Screenshot from 2023-09-13 13-06-08](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/76358f4b-6347-4328-8ebe-c3fcfcfd80fa)

![Screenshot from 2023-09-13 13-05-51](https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/ed4b8024-69c1-4628-bfec-d7a71bc6efbe)

**Comment by rawdaGastan** [comment]
Network contract shouldn't be deleted on failures because it is deployed separately
