### ISSUE TITLE
Create Nomad Module

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/terraform-provider-grid#765]
## Is your feature request related to a problem? Please describe

Deploying Nomad cluster requires repetitive code and could be simplified with a module.

## Describe the solution you'd like

Publishing a Terraform module would improve the user experience and simplify deploying a Nomad cluster.

- [Terrafrom docs on how to create a module](https://developer.hashicorp.com/terraform/language/modules/develop).
- [K8s module](https://github.com/threefoldtech/terraform-provider-grid/tree/development/modules/k8s-module).
- [Nomad server flist](https://hub.grid.tf/aelawady.3bot/abdulrahmanelawady-nomad-server-latest.flist.md).
- [Nomad client flist](https://hub.grid.tf/aelawady.3bot/abdulrahmanelawady-nomad-client-latest.flist.md).
- [Example of Nomad deployment using Terraform](https://gist.github.com/AbdelrahmanElawady/cc99e5ccbfb9f1a6e9412a8614c16982).

**Comment by xmonader** [comment]
Let's make sure the numbers of servers and clients are also configurable if not already

**Comment by Eslam-Nawara** [comment]
> Let's make sure the numbers of servers and clients are also configurable if not already

Server image allow fixed number of three servers, so now we're blocked by https://github.com/threefoldtech/tf-images/issues/181

**Comment by Eslam-Nawara** [comment]
WIP:

- [x] created the nomad module
- [x] implemented an example of the module
- [x] addressed all comments on the implementation

**Comment by Eslam-Nawara** [comment]
### Work Completed:
- nomad module was created to receive any number of servers (at least one) and zero or more clients
- user can use the module to deploy nomad cluster within the same node or in multiple nodes 
- usage example was added to illustrate how the module can be used

**Comment by rawdaGastan** [comment]
Can we add an integration test for nomad module (that way we can add how to verify it in the test)

**Comment by rawdaGastan** [comment]
I tried to deploy a nomad 3 server with a client then I tried to ssh to server1
- I tried `nomad status
```console
Error querying jobs: Get "http://127.0.0.1:4646/v1/jobs": dial tcp 127.0.0.1:4646: connect: connection refused
```

- I checked `zinit list`
```console
nomad: Blocked
sshd: Running
sshkey: Success
configure-node: Running
```

there is something wrong.

**Comment by rawdaGastan** [comment]
### Validation:

- tested the nomad module with the integration test and it worked 👍🏻 

```bash
--- PASS: TestNomad (245.74s)
    --- PASS: TestNomad/nomad_using_module (245.70s)
PASS
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests       245.793s
testing: warning: no tests to run
PASS
ok      github.com/threefoldtech/terraform-provider-grid/internal/provider      (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/threefoldtech/terraform-provider-grid/internal/provider/scheduler    (cached) [no tests to run]
```
