### ISSUE TITLE
VM negative tests for invalid cpu and invalid memory are not working

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#796]
automated nightly tests for virtual machines fails (they are using negative scenarios ,failing successfully but assertions needs to be fixed)

```

    --- FAIL: TestVM/vm_invalid_cpu (3.91s)
    --- FAIL: TestVM/vm_invalid_memory (3.92s)
```

**Comment by Eslam-Nawara** [comment]
- Both tests pass for me, can you link the workflow they failed in, or steps you used to generate the failure? @khaledyoussef24 
- there's just one problem, the workflow timeout before the vm tests get a chance to run, so the workflows time need to be increased

```console
➜  terraform-provider-grid git:(development_fix_k8s_nightly_test) ✗ go test ./integrationtests -run TestVM/vm_invalid_cpu
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests       3.291s
➜  terraform-provider-grid git:(development_fix_k8s_nightly_test) ✗ go test ./integrationtests -run TestVM/vm_invalid_memory
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests       3.085s
hub.com/threefoldtech/terraform-provider-grid/integrationtests       3.085s
```

**Comment by Eslam-Nawara** [comment]
Work Done:
- fixed the rest of the integration tests as there were a problem in the scheduler, still investigating the cause of the problem, but found out the scheduler works fine when specifying the farm id, so I run all tests in free farm, which is needed.
- now all tests run just fine except `vm_public_ip` test, which most probably because of no enough resources in devnet.

**Comment by rawdaGastan** [comment]
### Steps:

#### vm_invalid_cpu test passed ✅ 
```console
--- PASS: TestVM (3.32s)
    --- PASS: TestVM/vm_invalid_cpu (3.29s)
PASS
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests 
```

#### vm_invalid_memory test passed ✅ 
```console
--- PASS: TestVM (3.10s)
    --- PASS: TestVM/vm_invalid_memory (3.07s)
PASS
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests  
```

#### vm_public_ip skipped ⏸️ 
```console
--- PASS: TestVM (7.65s)
    --- SKIP: TestVM/vm_public_ip (7.64s)
PASS
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests   
```

Verified ✅
