### ISSUE TITLE
Scheduler doesn't return nodes (no available nodes)

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/terraform-provider-grid#806]
### Problem

- scheduler doesn't return nodes and always displays no nodes available

### Steps

- Try k8s example (https://github.com/threefoldtech/terraform-provider-grid/tree/development/examples/resources/k8s)

**Comment by Eslam-Nawara** [comment]
Verification: 
tested the single_vm test that failed due to scedular problem and now working fine 
```console 
--- PASS: TestVM (59.55s)
    --- PASS: TestVM/single_vm (59.53s)
PASS
ok      github.com/threefoldtech/terraform-provider-grid/integrationtests       59.589s
```
