### ISSUE TITLE
some examples needs to be updated

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#904]
some examples needs to be updated to work well.

single node example :
<img width="1183" alt="Screenshot 2024-03-18 at 2 34 02 PM" src="https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/b06285d1-ac97-4deb-b86e-da81fa5ed3e5">
the source link is not right it should be `      source = "threefoldtech/grid" `

for other examples version should be added because  `planetary-ip` which is not recognized it should be `planetary` unless we used     `version = "1.10.0"`
so should the version should be added for all of the examples ?

<img width="677" alt="Screenshot 2024-03-19 at 9 49 19 AM" src="https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/e0c1234b-6007-424f-afd1-49b69811b65a">
<img width="417" alt="Screenshot 2024-03-19 at 9 49 39 AM" src="https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/19ed304e-9438-4b7e-ac4e-ce2ab76ca451">

outputs are still labeled as `ygg_ip`
<img width="151" alt="Screenshot 2024-03-19 at 10 04 09 AM" src="https://github.com/threefoldtech/terraform-provider-grid/assets/110984055/9254114c-a2d6-4261-b894-9389ea446ae3">
should it be labeled as the dashboard and other solutions as `planetary-ip` ?

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
please update it
