### ISSUE TITLE
Update usage of farmerbot

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/terraform-provider-grid#951]
When using `farm_id` option in the scheduler, it got stuck. After some investigations, it seems current farmerbot stuck-not working

**Comment by SalmaElsoly** [comment]
## Verification Steps: 
- deployed using a vm with [this script](https://github.com/threefoldtech/terraform-provider-grid/blob/development/integrationtests/vm/main.tf) specifying farm_id = 1 in schedule 
![Image](https://github.com/user-attachments/assets/c4508796-b207-4fd0-87c4-c0590187e0d4)


- Successfully deployed and ssh to the machine
![Image](https://github.com/user-attachments/assets/d6c1dcd5-af3a-42ad-9f53-a8d028816dd1)

- Listed in dashboard
![Image](https://github.com/user-attachments/assets/4461144b-96de-46e3-af70-904896c57a2e)
