### ISSUE TITLE
Add volume workload

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/terraform-provider-grid#959]
## Description

A new Volume workload has been added to [ZOS](https://github.com/threefoldtech/zos/pull/2270) and [grid-client](https://github.com/threefoldtech/tfgrid-sdk-go/issues/993). It should act the same as ZMounts with some extra enhancements in performance as it go through less layers of virtualization.

> Note: raw images are not supported

## Interface

The new workload is of type `volume` and has the same structure as ZMount:
```json
{
    "size": <size-in-bytes>
}
```

**Comment by Eslam-Nawara** [comment]
duplicated https://github.com/threefoldtech/terraform-provider-grid/issues/928
