### ISSUE TITLE
Use the same master's filst when adding a new worker to kubernetes cluster

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/terraform-provider-grid#964]
https://github.com/threefoldtech/tf-images/issues/292

**Comment by Eslam-Nawara** [comment]
#WIP:
- updated k8s resource to have flist only in the cluster and removed it from the nodes

- will resume working on this issue after the next release of the client (after merging https://github.com/threefoldtech/tfgrid-sdk-go/pull/1168 and https://github.com/threefoldtech/tfgrid-sdk-go/pull/1162)
