### ISSUE TITLE
No ssh key path

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/terraform-provider-grid#968]
I keep getting this error when following the provider example steps in the docs.
Even after exporting MNEMONIC. 

![image](https://github.com/user-attachments/assets/210ebc51-0d2e-44ad-bde4-4f21f0105c74)

**Comment by rawdaGastan** [comment]
Actually I checked the error, it couldn't find your ssh key file
@amiraabouhadid

**Comment by rawdaGastan** [comment]
Okay will close the issue.
