### ISSUE TITLE
Scheduler picks down node

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/terraform-provider-grid#970]
I tried running the single VM Mycelium example against mainnet: https://github.com/threefoldtech/terraform-provider-grid/tree/development/examples/resources/single_vm_mycelium

It uses the scheduler, and that's resulting in a down node getting involved and causing this error:

```console
╷
│ Error: could not generate deployments data: 2 errors occurred:
│ 	* failed to get node 31 endpoint: could not list node interfaces: context deadline exceeded
│ 	* failed to process network testvm
│ 
│ 
│ 
│   with grid_network.net1,
│   on main.tf line 36, in resource "grid_network" "net1":
│   36: resource "grid_network" "net1" {
│ 
╵
```

![image](https://github.com/user-attachments/assets/f85fe135-4c0d-4fba-9f02-29241d70b390)

**Comment by rawdaGastan** [comment]
I think there is something wrong with the node, I checked it's status and found it `UP`

![image](https://github.com/user-attachments/assets/1d7b1af7-0559-4c25-a2d0-27cde4b33c23)

but it is down in the dashboard

**Comment by rawdaGastan** [comment]
@scottyeager are you updated to the latest version?

**Comment by rawdaGastan** [comment]
@scottyeager Okay if you faced the issue again you can reopen it. Thanks!
