### ISSUE TITLE
Error: couldn't get node public config: context deadline exceeded.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/terraform-provider-grid#971]
- Issue reported over the tester's chat: https://t.me/threefoldtesting/15373
- NodeID_6968

![image](https://github.com/user-attachments/assets/60ba1d26-9ed7-4764-bc9f-c72fdc01d03e)

**Comment by scottyeager** [comment]
So this is an RMB call to the node, and I found these errors indicating RMB connection instability in the node's logs:

![image](https://github.com/user-attachments/assets/9df35522-7938-4e0f-8940-619f17e499f1)

I don't think the is a Terraform issue per se.

**Comment by scottyeager** [comment]
Actually updating the provider solved this issue.
