### ISSUE TITLE
Support testing using mycelium instead of ygg

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/terraform-provider-grid#977]
## Describe the solution you'd like

- Change the resulting ygg ips from tests to mycelium ips
-  Install and use mycelium in the integration tests workflow

**Comment by Nabil-Salah** [comment]
# 20-10-2024
support testing with mycelium for gateway_test, presearch_test, wireguard_test
faced error with k8s_using_module_test and nomad_test as there modules fails and will be solved in another issue

**Comment by SalmaElsoly** [comment]
### 20-10-2024:
support mycelium in private gateway, k8s, preetube, mattermost, qsfs, vm and taiga . --> all was tested locally qsfs failed with error (can't find deployment or could not mount qsfs) 
testing of invalid config failed due to different error string shown will be modified

**Comment by rawdaGastan** [comment]
Tested using integration tests workflow (except qsfs it has a problem but not with this change)
