### ISSUE TITLE
Cannot delete VM 

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/terraform-provider-grid#978]
Cannot delete VM deployed on Terraform 
As per  Test case: [TC1167](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289581)

### Steps to Reproduce

bug environment:

1. OS: `ubuntu`
2. NETWORK: `dev`

![image](https://github.com/user-attachments/assets/bdd54949-ea44-47a8-8b04-bbad842b238d)

**Comment by rawdaGastan** [comment]
for dev, please use the latest version because the chain is updated
