### ISSUE TITLE
Missing required argument

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/terraform-provider-grid#979]
Please check Test cases: [TC325](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289582), [TC1169](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289584), [TC1170](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289585), [TC609](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1254318&selected=33334885)

![image](https://github.com/user-attachments/assets/dac39e12-f0b2-437d-bc06-cb6a63991260)

same case here: [TC613](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1254318&selected=33334886) in mount folder

![image](https://github.com/user-attachments/assets/ed7fa7f4-ebff-420b-ad94-7003ebb7660e)

same case here: [TC618](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1254318)

![image](https://github.com/user-attachments/assets/92eb0cfa-2b43-4446-ade3-fea43861ca38)

same case: [TC620](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1254318)

![image](https://github.com/user-attachments/assets/c1c0e453-3822-433b-9ee8-6bc6a4be3907)

**Comment by rawdaGastan** [comment]
what is the version you are using?

**Comment by samaradel** [comment]
Terraform ```v1.9.7```

**Comment by rawdaGastan** [comment]
We are on `v1.11.2-dev`

**Comment by samaradel** [comment]
I can't find ```v1.11.2-dev``` in [releases](https://github.com/hashicorp/terraform/releases) page

**Comment by rawdaGastan** [comment]
I mean our terraform version :D

**Comment by xmonader** [comment]
@samaradel reopen if still valid.

**Comment by samaradel** [comment]
It is not valid after updating the version
