### ISSUE TITLE
VM using mycelium example needs to be updated

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#983]
VM using mycelium example script fails while deploying and needs to be updated
<img width="1680" alt="Screenshot 2024-11-05 at 2 21 33 PM" src="https://github.com/user-attachments/assets/fae06807-5f15-434a-8ac9-5af5f2069c27">

**Comment by khaledyoussef24** [comment]
and same for single node script

**Comment by rawdaGastan** [comment]
I think you are using an older version

**Comment by khaledyoussef24** [comment]
updated to latest release and ran fine with latest version
