### ISSUE TITLE
choosing network is not working

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/terraform-provider-grid#984]
while running examples, I tried to deploy on Devnet and Qanet and it showed this strange error

<img width="675" alt="Screenshot 2024-11-05 at 2 26 55 PM" src="https://github.com/user-attachments/assets/1e407fff-1424-4873-9527-690fdbaa26e0">
<img width="684" alt="Screenshot 2024-11-05 at 2 35 45 PM" src="https://github.com/user-attachments/assets/ac180143-8041-4f2a-a2c6-fda4a2a6493f">

**Comment by rawdaGastan** [comment]
removing quotations solved the problem
